name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*' # semver, will override latest
      - '*-preview' # preview, won't override latest
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allow manual trigger

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser For Gofer/Spire
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f .github/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}